# Generated by Django 4.2.5 on 2024-05-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
